### ISSUE TITLE
Is this a bitCoin wallet or standard eWallet?

### ISSUE THREAD

**Issue by hitinder** [LykkeCity/WalletBackEnd#43]
I just want to know if its a bitcoin wallet or eWallet that can be used for payments?

**Comment by bijakatlykkex** [comment]
It is the backend layer used by Lykke to interface with Bitcoin blockchain. I personally do not consider this as a wallet although this could be used for building and sending transactions the hard way.

Lykke wallet is currently available for ios: https://appsto.re/ru/Dwjvcb.i and Android: https://play.google.com/store/apps/details?id=com.lykkex.LykkeWallet
